server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/Users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /staffs/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-67627430.okta.com/oauth2/default
    audience: api://default
    client-id: 0oam3dymkgbQ7FqgF5d7
    client-secret: QIo2k3EJnJ8xdnU6B2S4MTU4zSvbsdCwCjq_MeSq4ARmf0i_1WbYidU3zX14Lxx8
    scopes: openid, profile, email, offline_access